# THIS IS NOT TO BE USED FOR PERSONAL DEPLOYMENTS!
# Internal Docker Compose Image used for internal testing deployments

services:
  hoppscotch-aio:
    container_name: hoppscotch-aio
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: aio
    environment:
      # DATABASE_URL is read from the .env file to allow the backend to connect with an external database.
      # This allows the backend to retain existing data and prevents database resets during deployments.
      # DATABASE_URL=postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch
      - ENABLE_SUBPATH_BASED_ACCESS=true
    env_file:
      - ./.env
    ports:
      - "80:80"
    command: ["sh", "-c", "pnpm exec prisma migrate deploy && node /usr/src/app/aio_run.mjs"]
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 2s
      timeout: 10s
      retries: 30

